version: '3'
services:
  places-client:
    container_name: places-client
    build:
      context: ./places_client
    ports:
      - "8100:8100"

  places-server:
    container_name: places-server
    build:
      context: ./places_server
    ports:
      - "8200:8200"