version: '3'
services:
  places-client:
    build:
      context: ./places_client
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    networks:
      - app

  places-server:
    build:
      context: ./places_server
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    networks:
      - app

networks:
  app: