"""empty message

Revision ID: c1ce7b390db8
Revises: 
Create Date: 2024-04-13 15:19:42.028454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ce7b390db8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placelist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placelist_place_link',
    sa.Column('placelist_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['placelist_id'], ['placelist.id'], ),
    sa.PrimaryKeyConstraint('placelist_id', 'place_id')
    )
    op.create_table('user_created_placelist_link',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('placelist_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['placelist_id'], ['placelist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'placelist_id')
    )
    op.create_table('user_saved_placelist_link',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('placelist_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['placelist_id'], ['placelist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'placelist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_placelist_link')
    op.drop_table('user_created_placelist_link')
    op.drop_table('placelist_place_link')
    op.drop_table('user')
    op.drop_table('placelist')
    op.drop_table('place')
    # ### end Alembic commands ###
