name: Check
on: push
jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          prettier: true
          eslint_dir: ./places_client
          prettier_dir: ./places_client


  lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Activate virtual environment
        run: source $(poetry env info --path)/bin/activate
      - name: Lint
        run: make lint