name: Check
on: push
jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: places_client/package.json
      - run: |
          npm install
          npm run lint
        working-directory: places_client


  # lint-server:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up Python 3.12
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.12
  #     - name: Install dependencies
  #       run: |
  #         pip install poetry
  #         poetry install --with dev
  #       working-directory: ./places_server
  #     - name: Activate virtual environment
  #       run: source $(poetry env info --path)/bin/activate
  #     - name: Lint
  #       run: make lint