name: Deploy
on:
  push:
      branches:
        - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: 
      - Check
    types: 
      - completed

jobs:
  good:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 1
