name: Deploy
on: push

jobs:
  # lint-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache-dependency-path: places_client/package.json
  #     - run: |
  #         npm install
  #         npm run lint
  #       working-directory: places_client
  #       continue-on-error: true


  # lint-server:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.12
  #     - run: |
  #         pip install poetry==1.7.1
  #         poetry install --with dev --no-root && rm -rf /tmp/poetry_cache
  #         make lint
  #       working-directory: places_server
  #       continue-on-error: true

  # test-server:
  #   runs-on: ubuntu-latest
  #   needs: [lint-server]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.12
  #   - name: Install dependencies
  #     run: |
  #       pip install poetry==1.7.1
  #       poetry install --with test --no-root && rm -rf /tmp/poetry_cache
  #       poetry run pytest
  #     working-directory: places_server

  deploy:
    runs-on: ubuntu-latest
    # needs: [test-server, lint-client]
    if: github.ref_name == 'main'
    steps:
    - uses: actions/checkout@v2
    - uses: appleboy/ssh-action@v1.0.3
      env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        envs: JWT_SECRET_KEY,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,DATABASE_URL
        script: |
          rm -rf places
          git clone https://github.com/asokolkov/places.git
          cd places
          sudo docker compose up
