name: Deploy
on: push

jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: places_client/package.json
      - run: |
          npm install
          npm run lint
        working-directory: places_client
        continue-on-error: true


  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - run: |
          pip install poetry==1.7.1
          poetry install --with dev --no-root && rm -rf /tmp/poetry_cache
          make lint
        working-directory: places_server
        continue-on-error: true

  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install poetry==1.7.1
        poetry install --with test --no-root && rm -rf /tmp/poetry_cache
        poetry run pytest
      working-directory: places_server

  te:
    runs-on: ubuntu-latest
    needs: [test-server]
    if: github.ref_name == 'main'
    steps:
    - run: echo 1
